<?php

namespace Otus\Doctors\Models\Lists;

use Bitrix\Main\Entity;
use Bitrix\Main\Entity\ReferenceField;
use Otus\Doctors\Models\AbstractIblockPropertyValuesTable;
use \Otus\Doctors\Models\Lists\DoctorsProceduresPropertyValuesTable;
class DoctorsPropertyValuesTable extends AbstractIblockPropertyValuesTable
{
    public const IBLOCK_ID = 16;

    public static function getMap(): array
    {
        $map = [
            'PROCEDURE' => new Entity\ReferenceField(
                'PROCEDURE',
                DoctorsProceduresPropertyValuesTable::class,
                ['=this.PROCEDURE_ID' => '=ref.IBLOCK_ELEMENT_ID']
            )
        ];

       // return array_merge(parent::getMap(),$map); // TODO: Change the autogenerated stub
        return parent::getMap()+$map; // TODO: Change the autogenerated stub

    }
}
